{"name": "test_setup_failed_1", "status": "broken", "statusDetails": {"message": "AttributeError: 'function' object has no attribute 'pytestmark'", "trace": "self = <test_setup.TestSetUp object at 0x1272e5730>, method = <bound method TestSetUp.test_setup_failed_1 of <test_setup.TestSetUp object at 0x1272e5730>>\n\n    def setup_method(self, method):\n        \"\"\"\n        setup method.\n        :return: None\n        \"\"\"\n        self.class_data.append(method.__name__)\n        print(f\"setup method {method.__name__}\")\n        allure.attach(f\"setup method {method.__name__}\", name=\"setup method\",\n                      attachment_type=allure.attachment_type.TEXT)\n    \n        if method.__name__ == \"test_setup_failed_1\":\n            self.valid = False\n    \n        if method.__name__.startswith(\"test_setup_failed\"):\n            # get number from the test parm\n>           for mark in method.pytestmark:\nE           AttributeError: 'function' object has no attribute 'pytestmark'\n\ntests/tests_setup/test_setup.py:40: AttributeError"}, "description": "\n        test setup failed\n        :return: None\n        ", "start": 1722076999055, "stop": 1722076999055, "uuid": "c12c311a-3539-47c3-9801-c16189e6c8a8", "historyId": "480188b666ba4a903c0381489fddd690", "testCaseId": "480188b666ba4a903c0381489fddd690", "fullName": "tests.tests_setup.test_setup.TestSetUp#test_setup_failed_1", "labels": [{"name": "tag", "value": "setup"}, {"name": "tag", "value": "xdist_group(name='setup')"}, {"name": "parentSuite", "value": "tests.tests_setup"}, {"name": "suite", "value": "test_setup"}, {"name": "subSuite", "value": "TestSetUp"}, {"name": "host", "value": "Aymans-MacBook-Pro.local"}, {"name": "thread", "value": "12207-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_setup.test_setup"}]}